apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: k2wsit0ir-go 
  janus-idp.io/tekton: k2wsit0ir-go
  backstage.io/kubernetes-id: k2wsit0ir-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k2wsit0ir-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml